Add new posto.pem certificate file (#5)
country: Brasil environment: dev certificates: [client]

diff --git a/.github/workflows/update_bucket.yml b/.github/workflows/update_bucket.yml
--- a/.github/workflows/update_bucket.yml
+++ b/.github/workflows/update_bucket.yml
@@ -1,93 +1,34 @@
-name: Deploy Certificates to S3
+name: Synchronize Certificates to S3
 
 on:
-  workflow_dispatch:
-    inputs:
-      country:
-        description: 'Select the country: Brasil'
-        required: true
-        default: 'Brasil'
-      environment:
-        description: 'Select the environment: DEV'
-        required: true
-        default: 'DEV'
+  pull_request:
+    types: [ opened, synchronize, ready_for_review ]
 
 jobs:
-  deploy:
+
+  check-squash-commit-message:
     runs-on: ubuntu-latest
-    env:
-      PATH_TO_ENV: "${{ github.event.inputs.country }}/${{ github.event.inputs.environment }}"
-      PATH_TO_CERTIFICATE: "${{ github.event.inputs.country }}/${{ github.event.inputs.environment }}/certificates"
-      COUNTRY: "${{ github.event.inputs.country }}"
-      ENVIRONMENT: "${{ github.event.inputs.environment }}"
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Load Environment Configurations
-        run: |
-          chmod +x src/scripts/env.sh
-          src/scripts/env.sh ${{ env.PATH_TO_ENV }}/config.env
-
-      - name: Verify Directory Structure and Configuration File
-        run: |
-          if [ ! -f "${{ env.PATH_TO_ENV }}/config.env" ]; then
-            echo "Error: config.env file not found." >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-
-          if [ ! -d "${{ env.PATH_TO_CERTIFICATE }}/${{ env.TRUSTSTORE }}" ]; then
-            echo "Error: certificates/${{ env.TRUSTSTORE }} directory not found." >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-
-          if [ ! -d "${{ env.PATH_TO_CERTIFICATE }}/${{ env.TLS }}" ]; then
-            echo "Error: certificates/${{ env.TLS }} directory not found." >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-          echo "All directory structure checks have passed successfully."
-
-      - name: Verify variables in config.env
-        env:
-          REQUIRED_VARS: "AWS_REGION BUCKET_NAME TRUSTSTORE TLS"
-        run: |
-          IFS=' ' read -r -a REQUIRED_VARS_ARRAY <<< "$REQUIRED_VARS"
-          MISSING_VARS=()
-          for VAR in "${REQUIRED_VARS_ARRAY[@]}"; do
-            if ! grep -qE "^${VAR}=" ${{ env.PATH_TO_ENV }}/config.env; then
-              MISSING_VARS+=("$VAR")
-            fi
-          done  
-          if [ ${#MISSING_VARS[@]} -ne 0 ]; then
-            echo "Error: The following variables are missing in config.env: ${MISSING_VARS[*]}" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-
-          echo "All necessary variables are defined in config.env."
-
-      - name: Set up Python
-        uses: actions/setup-python@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
         with:
-          python-version: '3.12'
+          fetch-depth: 0
 
-      - name: Install Requirements
-        run: pip install -r src/requirements.txt
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
-
-      - name: Sync files to S3
-        run: python src/main/main.py
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ env.AWS_REGION }}
-
-      - name: Publish Report to Job Summary
+      - name: Check Commit Message
         run: |
-          echo "### S3 Sync Report" >> $GITHUB_STEP_SUMMARY
-          cat s3_sync_report.md >> $GITHUB_STEP_SUMMARY
-        
+          SQUASH_MSG=$(git log --format=%B -n 1 HEAD)
+          echo "Squash Commit Message: $SQUASH_MSG"
+          COMMIT_REGEX='^(country): \w{0,20} (environment): \w{0,5} certificates: \[[\w,]{0,50}\]$'
+          if ! [[ "$SQUASH_MSG" =~ $COMMIT_REGEX ]]; then
+            echo "Commit message does not meet the required template"
+            exit 1
+          fi
+
+  sync_certificates:
+    needs: [ check-squash-commit-message ]
+    uses: lisboajeff/bucket_python/.github/workflows/action.yml@main
+    with:
+      country: "${{ github.event.inputs.country }}"
+      environment: "${{ github.event.inputs.environment }}"
+      certificates: "${{ github.event.inputs.country }}/${{ github.event.inputs.environment }}/certificates"
+    secrets: inherit
