Update commit message check to title message check
This commit modifies the .github/workflows/updated_bucket.yml file to change the validation from commit messages to title messages. This is to align with our new policy of using pull request titles, instead of commit messages, as primary communication tool.

diff --git a/.github/workflows/update_bucket.yml b/.github/workflows/update_bucket.yml
--- a/.github/workflows/update_bucket.yml
+++ b/.github/workflows/update_bucket.yml
@@ -14,13 +14,13 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Check Commit Message
+      - name: Check Title Message
         run: |
-          SQUASH_MSG=$(git log --format=%B -n 1 HEAD)
-          echo "Squash Commit Message: $SQUASH_MSG"
-          COMMIT_REGEX='^(country): \w{0,20} (environment): \w{0,5} certificates: \[[\w,]{0,50}\]$'
-          if ! [[ "$SQUASH_MSG" =~ $COMMIT_REGEX ]]; then
-            echo "Commit message does not meet the required template"
+          TITLE=${{ github.event.pull_request.title }}
+          echo "Title Message: TITLE"
+          TITLE_REGEX='^(country): \w{0,20} (environment): \w{0,5} certificates: \[[\w,]{0,50}\]$'
+          if ! [[ "TITLE" =~ TITLE_REGEX ]]; then
+            echo "Title message does not meet the required template"
             exit 1
           fi
 
