Update regex and error messaging in update_bucket workflow
The previous regex for checking the pull request's title in the update_bucket GitHub action has been modified. This commit simplifies the pattern and accommodates more character types. In addition, the title message is now included in the error message when the title does not match the required template, thereby improving clarity.

diff --git a/.github/workflows/update_bucket.yml b/.github/workflows/update_bucket.yml
--- a/.github/workflows/update_bucket.yml
+++ b/.github/workflows/update_bucket.yml
@@ -17,10 +17,9 @@ jobs:
       - name: Check Title Message
         run: |
           TITLE="${{ github.event.pull_request.title }}"
-          echo "Title Message: $TITLE"
-          TITLE_REGEX='^(country): \w{0,20} (environment): \w{0,5} certificates: \[[\w,]{0,50}\]$'
-          if ! [[ "TITLE" =~ $TITLE_REGEX ]]; then
-            echo "Title message does not meet the required template"
+          TITLE_REGEX='^country [a-zA-Z]{0,20} environment [a-zA-Z]{0,5} certificates [[a-zA-Z,][a-zA-Z0-9,]{0,49}]$'
+          if ! [[ "$TITLE" =~ $TITLE_REGEX ]]; then
+            echo "Title message ($TITLE) does not meet the required template"
             exit 1
           fi
 
